app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    defaults:  { _locale: fr }
    requirements:
        _locale: be|nl|fr|en

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    defaults:  { _locale: fr }
    requirements:
        _locale: be|nl|fr|en

root:
    path: /
    defaults:
        _controller: "FrameworkBundle:Redirect:urlRedirect"
        path: /fr/index
        permanent: true

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}
    defaults:  { _locale: fr }
    requirements:
        _locale: be|nl|fr|en