security:
    encoders:
        UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/{_locale}/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:   ^/{_locale}/(login$|register|resetting)
            anonymous: ~

        main:
            pattern: ^/
            anonymous: ~
            provider:  main
            form_login:
                login_path:   admin.login
                check_path:   fos_user_security_check
            logout:
                path:   fos_user_security_logout
                target: /

    access_control:
        - { path: ^/bo, roles: ROLE_ADMIN }